version: '3.8'

services:
  grpc-server:
    container_name: grpc-server
    volumes:
      - ./:/grpc-server
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    command: sh -c 'air'